### PR TITLE
Inventory

### PR DESCRIPTION
**Pull request by gamirou**
Inventory bar is rendered now.

### CODE REVIEW

**Comment by Hoolean** [comment]
Nice work!

Looks like there's a merge conflict, I think that's just because this branch branched off of the health branch instead of master. This shouldn't cause any problems when we come to merging into master though, as health is already merged in.

One other small thing, if we're changing the height of a window (which is almost definitely a good idea) we also need to change how we center things on screen, either by changing the constant or by calculating it on-the-fly with the window dimensions.

https://github.com/neontribe/untangled-game/blob/a2cdae1b737b8f86796c1223c28b95b3e816e37e/untangled-2018/game/systems/rendersystem.py#L42

Apart from that, all looks well. We'll probably leave this PR open until there's some logic behind the inventory, so people don't get confused by the bar, but this is a great start. :)

**Comment by gamirou** [comment]
I changed line 42 to the code below because instead of typing 512, now it calculates on the fly the half of the width and the half of the height.

`screen_pos = (rel_pos[0] + game.framework.dimensions[0] / 2, rel_pos[1] + game.framework.dimensions[1] / 2)`

While I was testing, I noticed a suitable height would be 824px. Should we change the current height to 824?

**Comment by Hoolean** [comment]
Yeah, sounds good, I think 824px is sensible.

**Comment by Hoolean** [comment]
We've agreed to merge after animated items are included; the code looks ready :)

**Comment by gamirou** [comment]
I included animated items. It is ready to merge now.

**Comment by gamirou** [comment]
I included the animated items. The code is **ready to merge** :)

**Pull request merged**
